name: CI

on:
  push:
    branches: [ master, draft, frontend ]
  pull_request:
    branches: [ master, draft ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Dependencies    # 의존 파일 설치
        run: cd frontend && npm install

      - name: test                   # React test
        run: npm start
